force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <label>Meetup</label>
    <nameField>
        <label>Meetup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup__c/fields/Registration_Limit__c.field-meta.xml
<CustomField>
    <fullName>Registration_Limit__c</fullName>
    <label>Registration Limit</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/RegistrationCode__c.field-meta.xml
<CustomField>
    <fullName>RegistrationCode__c</fullName>
    <displayFormat>{00000000}</displayFormat>
    <label>RegistrationCode</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meetup_Registration__c/Meetup_Registration__c.object-meta.xml
<CustomObject>
    <label>Meetup Registration</label>
    <nameField>
        <displayFormat>MR-{00000}</displayFormat>
        <label>Meetup Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetup Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup_Registration__c/fields/Meetup__c.field-meta.xml
<CustomField>
    <fullName>Meetup__c</fullName>
    <label>Meetup</label>
    <referenceTo>Meetup__c</referenceTo>
    <relationshipLabel>Meetup Registrations</relationshipLabel>
    <relationshipName>Meetup_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RegistrationController.cls
/*
	---------------------------------------------------------------------------------------------------------------------------
	Author:			Lyndi WK 
	Description:	Controller class for registrationForm LWC
    Test Class:     Registration Controller Test

	History
	<Date>			<Authors Name>		<User Story>		<Brief Description of Change>
	2021-06-26  	Lyndi WK			        			Class Creation
	---------------------------------------------------------------------------------------------------------------------------
*/

public with sharing class RegistrationController {

    // ************************************************************************************ //
	// ** Description:  Used to query Meetup data for Registration Form                  ** //
	// ** Inputs: String Registration Code                                               ** //
	// ** Outputs: Associated Meetup record                         			         ** //														 
	// ************************************************************************************ //
    
    @AuraEnabled(cacheable=true)
    public static Meetup__c getMeetupRcd(String regCode) {
        
        // Query for Meetup Data
        List<Meetup__c> meetups =   [SELECT Id, Name, Registrations__c, Registration_Limit__c, Status__c FROM Meetup__c 
                                    WHERE RegistrationCode__c = :regCode];

        if (meetups.size() > 0) {
            return meetups[0];
        } else {
            return new Meetup__c();
        }
    }

    
    // ************************************************************************************ //
	// ** Description:  Used to validate Registration Form Data                          ** //
	// ** Inputs: Registrant Email & Meetup Id                                           ** //
	// ** Outputs: String Error Message                              			         ** //														 
	// ************************************************************************************ //

    @AuraEnabled(cacheable=true)
    public static String validateRegistration(String email, Id meetupId) {
        
        // Instantiate error message to be returned
        String errMsg = '';

        // Query for Meetup Data with 
        List<Meetup__c> meetups =   [SELECT Id, Name, Registrations__c, Registration_Limit__c, Status__c, 
                                    (SELECT Id FROM Meetup_Registrations__r WHERE Email__c = :email)
                                    FROM Meetup__c 
                                    WHERE Id = :meetupId];
        
        // Perform checks on registration to confirm it is valid
        if (meetups.size() > 0) {

            Meetup__c meetup = meetups[0];

            // If there is already a Meetup Registration using the same Email, prevent registration
            if (meetup.Meetup_Registrations__r.size() > 0) {
                errMsg = 'Sorry, there is already a registration for this Meetup using the provided email!';
                return errMsg;
            }

            // If the Meetup status is Closed or at Capacity, prevent registration
            if (meetup.Status__c != 'Open' || meetup.Registrations__c >= meetup.Registration_Limit__c) {
                errMsg = 'Sorry, this Meetup is no longer open for registration!';
                return errMsg;
            }
        }

        return errMsg;
    }
}